// <auto-generated />
namespace CodeFirstDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class InttoDoublePrice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InttoDoublePrice));
        
        string IMigrationMetadata.Id
        {
            get { return "202211081838022_Int to Double Price"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
